apiVersion: v1
kind: Service

metadata:
  name: opservice-frontend
  namespace: opsentrix

spec: 
  selector:
    app: opfrontend
  
  ports:
    - port: 3000
      targetPort: 3000

  type: ClusterIP